On-Screen Keyboard icons
numixproject/numix-icon-theme pull request #1368
Opened 2020-07-27 22:03 UTC by palob

Fixes #1366

+ fixes to symbolic icons. Boy, the whole Numix base theme has got a lot room for improvements.

2020-07-28 08:11 UTC, palob commented
![Bildschirmfoto vom 2020-07-28 10-08-10](https://user-images.githubusercontent.com/7050624/88637490-81e53c80-d0ba-11ea-86bd-c8c820eda7d4.png)

For some reason ``keyboard-hide-symbolic`` isn't picked up but ``go-down-symbolic`` is shown instead.

2020-09-05 13:57 UTC, Foggalong requested changes
Pan down has been given the same icon as keyboard hide, but only in the standard theme. I assume this is in error?

2020-09-06 18:44 UTC, palob commented
Was a mistake indeed, fixed now.

2020-09-08 17:39 UTC, Foggalong approved these changes

2020-09-08 17:40 UTC, merged